image = "hashicorp/packer:1.3.1"
distro = "alpine"
os = "linux"

[options]
interactive = true
network = "host"
_mount = [
  "type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock"
]
tty = true

[apps]
packer = ["/bin/packer"]
